mapping_street = { 
			
		"St": "Street",
            "St.": "Street",
            "st": "Street",
            "street": "Street",
            "Street,": "Street",
            "Ave": "Avenue",
            "Ave.": "Avenue",
            "Avene": "Avenue",
            "Blvd": "Boulevard",
            "Blvd.": "Boulevard",
            "Boulevard,": "Boulevard",
            "Blvd,": "Boulevard",
            "Blvd.,": "Boulevard",
            "Dr": "Drive",
            "Dr.": "Drive",
            "Ct": "Court",
            "Ct.": "Court",
            "court": "Court",
            "Cv": "Cove",
            "cove": "Cove",
            "Cc": "Cove",
            "Pl": "Place",
            "Pl.": "Place",
            "lane": "Lane",
            "Ln": "Lane",
            "Rd": "Road", 
            "Rd.": "Road",
            "R": "Road",
            "Trl": "Trail",
            "Tr": "Trail",
            "Pkwy": "Parkway",
            "Hwy": "Highway",
            "HWY": "Highway",
            "Hwy,": "Highway",
            "H": "Highway",
            "I35": "Interstate Highway 35",
            "IH35": "Interstate Highway 35",
            "IH35,": "Interstate Highway 35",
            "IH-35": "Interstate Highway 35",
            "I-35": "Interstate Highway 35",
            "IH": "Interstate Highway",
            "I": "Interstate",
            "35,": "35",
            "main": "Main",
            "N": "North",
            "N.": "North",
            "Ovlk": "Overlook",
            "pass": "Pass",
            "Ps": "Pass",
            "W": "West",
            "W.": "West",
            "E": "East",
            "E.": "East",
            "texas": "Texas",
            "TX": "Texas",
            "FM": "Farm-to-Market Road",
            "F.M.": "Farm-to-Market Road",
            "U.S.": "United States",
            "US": "United States",
            "RM": "Ranch-to-Market Road",
            "RM1431": "Ranch-to-Market Road 1431",
            "RR": "Ranch Road",
            "S": "South",
            "S.": "South",
            "south": "South",
            "Bldg": "Building",
            "Bldg.": "Building",
            "Bld": "Building",
            "Ste": "Suite",
            "Ste,": "Suite",
            "STE": "Suite",
            "Ste.": "Suite",
            "suite": "Suite",
            "C": "Country",
            "church": "Church",
            "brigadoon": "Brigadoon",
            "Drive/Rd": "Drive/Road",
            "Mo-Pac": "MoPac", 
            "Avenue,Ste": "Avenue Suite",
            "suite#L131": "Suite L131"

            }